/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OperationService } from "../operation.service";
import { OperationCreateInput } from "./OperationCreateInput";
import { Operation } from "./Operation";
import { OperationFindManyArgs } from "./OperationFindManyArgs";
import { OperationWhereUniqueInput } from "./OperationWhereUniqueInput";
import { OperationUpdateInput } from "./OperationUpdateInput";
import { OperationLogFindManyArgs } from "../../operationLog/base/OperationLogFindManyArgs";
import { OperationLog } from "../../operationLog/base/OperationLog";
import { OperationLogWhereUniqueInput } from "../../operationLog/base/OperationLogWhereUniqueInput";
import { OperationDto } from "../OperationDto";

export class OperationControllerBase {
  constructor(protected readonly service: OperationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operation })
  async createOperation(
    @common.Body() data: OperationCreateInput
  ): Promise<Operation> {
    return await this.service.createOperation({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        num1: true,
        num2: true,
        result: true,
        operationType: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operation] })
  @ApiNestedQuery(OperationFindManyArgs)
  async operations(@common.Req() request: Request): Promise<Operation[]> {
    const args = plainToClass(OperationFindManyArgs, request.query);
    return this.service.operations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        num1: true,
        num2: true,
        result: true,
        operationType: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operation(
    @common.Param() params: OperationWhereUniqueInput
  ): Promise<Operation | null> {
    const result = await this.service.operation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        num1: true,
        num2: true,
        result: true,
        operationType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperation(
    @common.Param() params: OperationWhereUniqueInput,
    @common.Body() data: OperationUpdateInput
  ): Promise<Operation | null> {
    try {
      return await this.service.updateOperation({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          num1: true,
          num2: true,
          result: true,
          operationType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperation(
    @common.Param() params: OperationWhereUniqueInput
  ): Promise<Operation | null> {
    try {
      return await this.service.deleteOperation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          num1: true,
          num2: true,
          result: true,
          operationType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/operationLogs")
  @ApiNestedQuery(OperationLogFindManyArgs)
  async findOperationLogs(
    @common.Req() request: Request,
    @common.Param() params: OperationWhereUniqueInput
  ): Promise<OperationLog[]> {
    const query = plainToClass(OperationLogFindManyArgs, request.query);
    const results = await this.service.findOperationLogs(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        timestamp: true,

        operation: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/operationLogs")
  async connectOperationLogs(
    @common.Param() params: OperationWhereUniqueInput,
    @common.Body() body: OperationLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operationLogs: {
        connect: body,
      },
    };
    await this.service.updateOperation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/operationLogs")
  async updateOperationLogs(
    @common.Param() params: OperationWhereUniqueInput,
    @common.Body() body: OperationLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operationLogs: {
        set: body,
      },
    };
    await this.service.updateOperation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/operationLogs")
  async disconnectOperationLogs(
    @common.Param() params: OperationWhereUniqueInput,
    @common.Body() body: OperationLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operationLogs: {
        disconnect: body,
      },
    };
    await this.service.updateOperation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/add")
  @swagger.ApiOkResponse({
    type: OperationDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async AddNumbers(
    @common.Body()
    body: OperationDto
  ): Promise<OperationDto> {
    return this.service.AddNumbers(body);
  }

  @common.Post("/divide")
  @swagger.ApiOkResponse({
    type: OperationDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async DivideNumbers(
    @common.Body()
    body: OperationDto
  ): Promise<OperationDto> {
    return this.service.DivideNumbers(body);
  }

  @common.Post("/multiply")
  @swagger.ApiOkResponse({
    type: OperationDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async MultiplyNumbers(
    @common.Body()
    body: OperationDto
  ): Promise<OperationDto> {
    return this.service.MultiplyNumbers(body);
  }

  @common.Post("/subtract")
  @swagger.ApiOkResponse({
    type: OperationDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async SubtractNumbers(
    @common.Body()
    body: OperationDto
  ): Promise<OperationDto> {
    return this.service.SubtractNumbers(body);
  }
}
